name: barokah_cars_project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.0
  cupertino_icons: ^1.0.6
  firebase_core: ^2.30.0
  fluentui_system_icons: ^1.0.0
  flutter:
    sdk: flutter
  get: 4.6.6
  get_cli: ^1.8.1
  get_storage: ^2.1.1
  git: ^2.2.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/logos/
  uses-material-design: true
