name: barokah_cars_project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  carousel_slider: ^4.2.1
  circular_profile_avatar: ^2.0.5
  cloud_firestore: ^4.17.0
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.0
  firebase_database: ^10.5.5
  firebase_storage: ^11.7.7
  fluentui_system_icons: ^1.0.0
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.5
  get: 4.6.6
  get_cli: ^1.8.1
  git: ^2.2.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.1
  intl: ^0.17.0
  lottie: ^3.1.0
  random_string: ^2.3.1
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/banners/
  uses-material-design: true
